Initialisation of Matrix

In [2]:
import numpy as np

n = int(input("Enter the number of rows:"))

A=[]
B=[]

for i in range(0,n):
    a =[]
    print("Enter values of ", i,"th row of matrix A")
    for j in range(0,n):
         a.append(float(input()))
    A.append(a)
    print("\n")

print("Enter the values of B")
for i in range(0,n):
    B.append(float(input()))

A=np.reshape(A,(n,n))
B=np.reshape(B,(n,1))
print(A)
print(B)

Enter values of  0 th row of matrix A


Enter values of  1 th row of matrix A


Enter values of  2 th row of matrix A


Enter the values of B
[[ 4. -3.  1.]
 [-2.  1. -3.]
 [ 1. -1.  2.]]
[[-8.]
 [-4.]
 [ 3.]]


  Converting A matrix into Triangular matrix

In [7]:
for x in range(0,n) :
  print(A[x])
  B[x]=B[x]/A[x][x]
  A[x]=A[x]/A[x][x]
  print("A = ")
  print(A)
  print("B = ")
  print(B)
  print("==========")
  print(x)
  print("==========")
  for y in range(0,n) :
    if (y==x) :
      continue
    B[y]=B[y]-(B[x]*A[y][x])
    A[y]=A[y]-(A[x]*A[y][x])
    

[1. 0. 0.]
A = 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
B = 
[[-2.]
 [ 1.]
 [ 3.]]
0
[0. 1. 0.]
A = 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
B = 
[[-2.]
 [ 1.]
 [ 3.]]
1
[0. 0. 1.]
A = 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
B = 
[[-2.]
 [ 1.]
 [ 3.]]
2


In [8]:
print("The final value of X is :-")
print(B)

The final value of X is :-
[[-2.]
 [ 1.]
 [ 3.]]
